export const CAMPAIGN_SENDING = 'CAMPAIGN_SENDING';
export const CAMPAIGN_SENT_SUCCESS = 'CAMPAIGN_SENT_SUCCESS';
export const CAMPAIGN_SENT_ERROR = 'CAMPAIGN_SENT_ERROR';
export const CAMPAIGN_ADD_DATA = 'CAMPAIGN_ADD_DATA';
export const GET_CAMPAIGNS = 'GET_CAMPAIGNS';