export const LOGIN = 'LOGIN';
export const UPDATE_MATCHES = 'UPDATE_MATCHES';
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';
export const UPDATE_REMINDERS = 'UPDATE_REMINDERS';
export const UPDATE_APPLICANTS = 'UPDATE_APPLICANTS';
export const UPDATE_INVISIBLE = 'UPDATE_INVISIBLE';